### ISSUE TITLE
mysql-sys-master]$ mysql < sys_56.sql ERROR 1055 (42000) at line 48 in file: './views/p_s/processlist.sql': 'performance_schema.pps.PROCESSLIST_ID' isn't in GROUP BY

### ISSUE THREAD

**Issue by jwsintro** [MarkLeith/mysql-sys#47]
Pulled on 02/13/2015
mysql-sys-master]$ mysql < sys_56.sql
ERROR 1055 (42000) at line 48 in file: './views/p_s/processlist.sql': 'performance_schema.pps.PROCESSLIST_ID' isn't in GROUP BY

**Comment by MarkLeith** [comment]
This is already resolved in the development branch, version 1.4.0 will be released soon, please use the development branch in the interim.

**Comment by TexCarver** [comment]
This bug still exists in 1.4.0. Tested today with current master (which claims to be 1.4.0) and explicitly with dev 1.4.0.

**Comment by MarkLeith** [comment]
This is fixed in 1.5.0 for 5.6, with:

https://github.com/MarkLeith/mysql-sys/commit/7e677dc98c7c482c5d58896a3d01ef8970185ca9
